# This action generates a PDF from all of the game's writing.

name: Build PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - run: mkdir PDFs
      - uses: actions/checkout@v4
      - uses: docker://pandoc/latex
        with:
          args: >- # allows you to break string into multiple lines
            --from=markdown
            --to=pdf
            --output="PDFs/Writ of Rulers.pdf"
            README.md
      - uses: actions/upload-artifact@v4
        with:
          name: "Writ of Rulers"
          path: PDFs
