# This action generates a PDF from all of the game's writing.

name: Build PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Writ of Rulers File Order
        id: file_order
        run: echo "order=$(cat file_order.txt)" >> $GITHUB_OUTPUT

      - name: Convert Files with Pandoc
        uses: docker://pandoc/extra
        with:
          args: >-
            --from=markdown
            --to=pdf
            --output="Writ of Rulers.pdf"
            -H deeplists.tex
            ${{ steps.file_order.outputs.order }}

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Writ of Rulers"
          path: "Writ of Rulers.pdf"
          overwrite: true
