# This action generates a PDF from all of the game's writing.

name: Build PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Convert Files with Pandoc
        uses: docker://pandoc/extra
        with:
          args: >-
            --from=markdown
            --to=pdf
            --output="Writ of Rulers.pdf"
            -H deeplists.tex
            README.md
            "Misc/Table of Contents.md"
            "Core Mechanics/Formats of Play/Formats of Play.md"
            "Core Mechanics/Formats of Play/Formats of Play/Standalone.md"
            "Core Mechanics/Formats of Play/Formats of Play/Sidecar.md"

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Writ of Rulers"
          path: "Writ of Rulers.pdf"
          overwrite: true
