# This action generates a PDF from all of the game's writing.

name: Build PDF
on: push

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: Core Mechanics/**
          output_dir: PDFs
      - uses: actions/upload-artifact@v4
        with:
          name: "Writ of Rulers"
          path: PDFs
