# This action generates a PDF from all of the game's writing.

name: Build PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Convert Files with Pandoc
        uses: docker://pandoc/extra
        with:
          args: >-
            --from=markdown
            --to=pdf
            --output="Writ of Rulers.pdf"
            -H deeplists.tex
            --pdf-engine=xelatex
            --papersize=letter
            README.md
            "Core Mechanics/Formats of Play/Formats of Play.md"
            "Core Mechanics/Formats of Play/Formats of Play/Standalone.md"
            "Core Mechanics/Formats of Play/Formats of Play/Sidecar.md"
            "Core Mechanics/Key Terms.md"
            "Core Mechanics/Rounds/Rounds.md"
            "Core Mechanics/Rounds/Objectives.md"
            "Core Mechanics/Rounds/Evaluate Success of Objective.md"
            "Core Mechanics/Writs/Writs.md"
            "Core Mechanics/Writs/Writs/Advance Or Create An Agenda.md"
            "Core Mechanics/Writs/Writs/Change The Objective.md"
            "Core Mechanics/Writs/Writs/Deploy A Spy Network.md"
            "Core Mechanics/Writs/Writs/Make A Big Play.md"
            "Core Mechanics/Writs/Writs/Make A Prediction.md"
            "Core Mechanics/Writs/Writs/Order A Unit.md"
            "Core Mechanics/Writs/Writs/Send A Delegate.md"
            "Core Mechanics/Kingdoms/Kingdom Creation/Kingdom Creation.md"
            "Core Mechanics/Kingdoms/Kingdom Scales.md"
            "Core Mechanics/Kingdoms/Kingdom Creation/Ruler Creation.md"
            "Core Mechanics/Kingdoms/Kingdom Creation/Court Creation.md"
            "Core Mechanics/Warefare/Warefare in Bullet Points.md"
            "GM Focused/GM Agendas.md"
            "GM Focused/World Primers/The Great Pillars Are Dead.md"
            "Misc/Inspirations.md"
            "Misc/Special Thanks.md"

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Writ of Rulers"
          path: "Writ of Rulers.pdf"
          overwrite: true
